development:
  adapter: postgresql
  encoding: unicode
  database: r2013-04-05-ember-blog_development
  pool: 5
  username: Sean
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: r2013-04-05-ember-blog_test
  pool: 5
  username: Sean
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: r2013-04-05-ember-blog_production
  pool: 5
  username: Sean
  password:
